name: fitness
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
    sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  carousel_slider: ^4.2.1

  ff_navigation_bar_plus: ^0.1.5
  calendar_date_picker2: ^0.5.2
  uuid: ^3.0.4
  animated_icon: ^0.0.5
  video_player: ^2.6.1
  flutter_login_facebook: ^1.7.0
  flutter_slidable: ^2.0.0
  firebase_auth: ^4.4.0
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  flutter_screenutil: ^5.7.0
  fluttertoast: ^8.2.1
  email_auth: ^1.0.0
  image_picker: ^0.8.7+2
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.1
  curved_navigation_bar: ^1.0.3
  shared_preferences: ^2.1.0
  http: ^0.13.5
  google_sign_in: ^6.1.4
  animated_splash_screen: ^1.3.0
  modal_bottom_sheet: ^2.0.0
  firebase_core: ^2.9.0
  flutter_svg: ^2.0.5
  table_calendar: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/icons/
