name: fitness
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+8

environment:
    sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  firebase_auth: ^4.4.0
  email_auth: ^1.0.0
  image_picker: ^1.0.0
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.1
  http: ^0.13.5
  google_sign_in: ^6.1.4
  firebase_core: ^2.9.0
  flutter_svg: ^2.0.5
  email_validator: ^2.1.17
  youtube_player_flutter: ^8.1.2
  video_player: ^2.6.1
  url_launcher: ^6.1.11
  whatsapp_unilink: ^2.1.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0
  webview_flutter: ^4.4.1
  date_format: ^2.0.7
  timeago: ^3.6.0
  lottie: ^2.7.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/svg/
  - assets/png/
  - assets/json/

  fonts:
  
    - family: SpaceGrotesk
      fonts:
        - asset: fonts/SpaceGrotesk-Regular.ttf 

    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-VariableFont_wght.ttf
   
