name: fitness
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  ff_navigation_bar_plus: ^0.1.5
  firebase_auth: ^4.4.0
  email_auth: ^1.0.0
  image_picker: ^0.8.7+2
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.1
  http: ^0.13.5
  google_sign_in: ^6.1.4
  firebase_core: ^2.9.0
  flutter_svg: ^2.0.5
  table_calendar: ^3.0.8
  email_validator: ^2.1.17
  intl_phone_field: ^3.1.0
  youtube_player_flutter: ^8.1.2
  video_player: ^2.6.1
  gradient_slide_to_act: ^0.0.2
  icons_plus: ^4.0.0
  date_picker_timeline: ^1.2.3
  url_launcher: ^6.1.11
  whatsapp_unilink: ^2.1.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/icons/

  fonts:
   
    - family: TwCenMT
      fonts:
        - asset: fonts/TwCenMTStd-Light.otf
    - family: ITCAvant
      fonts:
        - asset: fonts/ITCAvantGardeStd-BkCn.ttf
