// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNZvcQ2-ebE7x-PzB9T2BcM-nRNxtNnX0',
    appId: '1:1009790740333:android:700a638a089fcc53acdc64',
    messagingSenderId: '1009790740333',
    projectId: 'fitnessjourney-48caa',
    databaseURL: 'https://fitnessjourney-48caa-default-rtdb.firebaseio.com',
    storageBucket: 'fitnessjourney-48caa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA-as_ztkvZsycRBYuuRWYL4jenhFV-Vs',
    appId: '1:1009790740333:ios:4d35cc81b062f544acdc64',
    messagingSenderId: '1009790740333',
    projectId: 'fitnessjourney-48caa',
    databaseURL: 'https://fitnessjourney-48caa-default-rtdb.firebaseio.com',
    storageBucket: 'fitnessjourney-48caa.appspot.com',
    androidClientId:
        '1009790740333-8c4gjb8kge1uu8vforp3qlhbstpv4fsh.apps.googleusercontent.com',
    iosClientId:
        '1009790740333-2i0tofj6o6cku30o4bm186nucln24od6.apps.googleusercontent.com',
    iosBundleId: 'com.fitness.journey',
  );
}
